name: Java CI with Maven (deploy)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest 

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: l3webapi
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

    - name: Configure le fuseau horaire
      run: |
        sudo ln -snf /usr/share/zoneinfo/Europe/Paris /etc/localtime
        echo "Europe/Paris" | sudo tee /etc/timezone
      shell: bash

    - name: Date
      run: date

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Test PostgreSQL Connection
      run: |
        psql -h 127.0.0.1 -U postgres -c "\l"
      env:
        PGPASSWORD: "l3webapi"

    - name: Create database schema
      run: |
        psql -h 127.0.0.1 -U postgres -d l3webapi -f create_user.sql
      env:
        PGPASSWORD: "l3webapi"
#    - name: Create database schema
#      run: |
#        psql -h 127.0.0.1 -U postgres -d l3webapi -f workflow_database/controlCoil_create.sql
 #     env:
 #       PGPASSWORD: "l3webapi"
        
#    - name: Insert data into database
#      run: |
#        psql -h 127.0.0.1 -U postgres -d controlCoil_test -f workflow_database/controlCoil_insert.sql
#      env:
#        PGPASSWORD: "l3webapi"
