name: .NET with PostgreSQL

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest 

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: l3webapi
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Test PostgreSQL Connection
      run: |
        psql -h 127.0.0.1 -U postgres -c "\l"
      env:
        PGPASSWORD: "postgres"

    - name: Create database schema
      run: |
        psql -h 127.0.0.1 -U postgres -d l3webapi -f create_user.sql
      env:
        PGPASSWORD: "postgres"
        
    - name: Create database schema
      run: |
        psql -h 127.0.0.1 -U postgres -d l3webapi -f create_db.sql
      env:
        PGPASSWORD: "postgres"

    - name: insert database schema
      run: |
        psql -h 127.0.0.1 -U l3webapi -d l3webapi -f insert_db.sql
      env:
        PGPASSWORD: "l3webapi"

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.104'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
    - name: Execute SELECT Query
      env:
        PGPASSWORD: l3webapi
      run: |
        psql -h localhost -U l3webapi -d l3webapi -c "SELECT * FROM games;"
        
    - name: Test
      run: dotnet test
      env:
        SQLConnectionString: 'Host=91.68.34.203;Port=5432;Database=l3webapi;Username=l3webapi;Password=l3webapi'
